### ISSUE TITLE
Documentation for using the package properly

### ISSUE THREAD

**Issue by abdul-razaq** [MelihTOKSARI/react-native-verto-typescript#1]
Hello, Thanks for building this wonderful react-native-verto package. I have gone through the repository and npm home page for this package but there seems to not be a documentation on how to use this package and the API it exposes. 

I'm looking to build a video chat mobile application with React Native and I need to connect to a backend server that uses Verto Freeswitch. Thank you.

**Comment by MelihTOKSARI** [comment]
ReadMe file is added.
